# {build} is required by AppVeyor to uniquely identify its builds on the url
# It is a continuously incrementing number so when used it violates the reset
# smaller build parts rule of semantic versioning. Therefore we introduce a
# second environment variable semantic_version.
version: 0.1.1.{build}

environment:
  version_functional: 0.1.0
  version_securestring: 0.1.2

configuration:
  - Debug
  - Release

install:
  - set semantic_version=%APPVEYOR_BUILD_VERSION:~0,5%
  - echo Version - %semantic_version%
  - nuget restore

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(semantic_version).{build}'
  assembly_file_version: '$(semantic_version).{build}'
  assembly_informational_version: '$(semantic_version)'

build:
  publish_nuget: true
  parallel: true
  verbosity: normal

after_test:
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\PackageSpecs\Recipes.Functional.nuspec" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_functional%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.Functional.%version_functional%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\PackageSpecs\Recipes.SecureString.nuspec" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_securestring%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.SecureString.%version_securestring%.nupkg"

deploy:
  - provider: NuGet
    on:
      branch: master
      configuration: Release
    api_key:
      secure: dUMLXnYuqF7ORswtDCtj2XgKlpLMKrXZrq9m/FEN2xu0vTClejXqADyxMEawTs2W
    skip_symbols: true
    artifact: /.*\.nupkg/
