# {build} is required by AppVeyor to uniquely identify its builds on the url
# It is a continuously incrementing number so when used it violates the reset
# smaller build parts rule of semantic versioning. Therefore we introduce a
# second environment variable semantic_version.
version: 0.10.0.{build}

os: Visual Studio 2015

environment:
  RunCodeAnalysis: true
  version_functional: 0.2.4
  version_securestring: 0.2.5
  version_securestringjsonconverter: 0.2.3
  version_inheritedtypejsonconverter: 0.4.4
  version_jsonconfiguration: 0.7.3
  version_formattablestring: 0.1.3
  version_progressreporter: 0.1.0

configuration:
  - Debug
  - Release

cache:
  - packages -> **\packages.config

install:
  - set semantic_version=%APPVEYOR_BUILD_VERSION:~0,6%
  - echo Version - %semantic_version%
  - nuget restore

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(semantic_version).{build}'
  assembly_file_version: '$(semantic_version).{build}'
  assembly_informational_version: '$(semantic_version)'

build:
  project: Build.proj
  parallel: true
  verbosity: normal

after_test:
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\Functional\Functional.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\Functional" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_functional%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.Functional.%version_functional%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\SecureString\SecureString.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\SecureString" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_securestring%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.SecureString.%version_securestring%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\SecureStringJsonConverter\SecureStringJsonConverter.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\SecureStringJsonConverter" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_securestringjsonconverter%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.SecureStringJsonConverter.%version_securestringjsonconverter%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\InheritedTypeJsonConverter\InheritedTypeJsonConverter.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\InheritedTypeJsonConverter" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_inheritedtypejsonconverter%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.InheritedTypeJsonConverter.%version_inheritedtypejsonconverter%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\JsonConfiguration\JsonConfiguration.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\JsonConfiguration" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_jsonconfiguration%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.JsonConfiguration.%version_jsonconfiguration%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\FormattableString\FormattableString.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\FormattableString" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_formattablestring%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.FormattableString.%version_formattablestring%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\ProgressReporter\ProgressReporter.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\ProgressReporter" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_progressreporter%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.ProgressReporter.%version_progressreporter%.nupkg"

deploy:
  - provider: NuGet
    on:
      branch: master
      configuration: Release
    api_key:
      secure: dUMLXnYuqF7ORswtDCtj2XgKlpLMKrXZrq9m/FEN2xu0vTClejXqADyxMEawTs2W
    skip_symbols: true
    artifact: /.*\.nupkg/
