# {build} is required by AppVeyor to uniquely identify its builds on the url
# It is a continuously incrementing number so when used it violates the reset
# smaller build parts rule of semantic versioning. Therefore we introduce a
# second environment variable semantic_version.
version: 0.18.2.{build}

os: Visual Studio 2015

environment:
  RunCodeAnalysis: true
  version_functional: 0.2.6
  version_securestring: 1.0.0
  version_securestringjsonconverter: 0.4.0
  version_inheritedtypejsonconverter: 0.8.0
  version_camelstrictconstructorresolver: 0.3.0
  version_jsonconfiguration: 0.14.1
  version_formattablestring: 0.1.5
  version_progressreporter: 0.3.1
  version_base64urlextensions: 0.1.1
  version_jsonwebtoken: 0.2.0
  version_googleauthorizer: 0.2.0
  version_googledrive: 0.2.0

configuration:
  - Debug
  - Release

cache:
  - packages -> **\packages.config

install:
  - set semantic_version=%APPVEYOR_BUILD_VERSION:~0,6%
  - echo Version - %semantic_version%
  - nuget restore

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(semantic_version).{build}'
  assembly_file_version: '$(semantic_version).{build}'
  assembly_informational_version: '$(semantic_version)'

build:
  project: Build.proj
  parallel: true
  verbosity: normal

after_test:
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\Functional\Functional.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\Functional" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_functional%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.Functional.%version_functional%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\SecureString\SecureString.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\SecureString" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_securestring%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.SecureString.%version_securestring%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\SecureStringJsonConverter\SecureStringJsonConverter.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\SecureStringJsonConverter" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_securestringjsonconverter%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.SecureStringJsonConverter.%version_securestringjsonconverter%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\InheritedTypeJsonConverter\InheritedTypeJsonConverter.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\InheritedTypeJsonConverter" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_inheritedtypejsonconverter%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.InheritedTypeJsonConverter.%version_inheritedtypejsonconverter%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\CamelStrictConstructorContractResolver\CamelStrictConstructorContractResolver.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\CamelStrictConstructorContractResolver" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_camelstrictconstructorresolver%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.CamelStrictConstructorContractResolver.%version_camelstrictconstructorresolver%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\JsonConfiguration\JsonConfiguration.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\JsonConfiguration" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_jsonconfiguration%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.JsonConfiguration.%version_jsonconfiguration%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\FormattableString\FormattableString.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\FormattableString" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_formattablestring%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.FormattableString.%version_formattablestring%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\ProgressReporter\ProgressReporter.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\ProgressReporter" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_progressreporter%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.ProgressReporter.%version_progressreporter%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\Base64UrlExtensions\Base64UrlExtensions.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\Base64UrlExtensions" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_base64urlextensions%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.Base64UrlExtensions.%version_base64urlextensions%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\JsonWebToken\JsonWebToken.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\JsonWebToken" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_jsonwebtoken%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.JsonWebToken.%version_jsonwebtoken%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\GoogleAuthorizer\GoogleAuthorizer.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\GoogleAuthorizer" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_googleauthorizer%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.GoogleAuthorizer.%version_googleauthorizer%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\Recipes\GoogleDrive\GoogleDrive.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\Recipes\GoogleDrive" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_googledrive%" -OutputDirectory "%TEMP%"
  - appveyor PushArtifact "%TEMP%\Spritely.Recipes.GoogleDrive.%version_googledrive%.nupkg"

deploy:
  - provider: NuGet
    on:
      branch: master
      configuration: Release
    api_key:
      secure: dUMLXnYuqF7ORswtDCtj2XgKlpLMKrXZrq9m/FEN2xu0vTClejXqADyxMEawTs2W
    skip_symbols: true
    artifact: /.*\.nupkg/
