// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IJsonWebTokenSigner.cs">
//     Copyright (c) 2016. All rights reserved. Licensed under the MIT license. See LICENSE file in
//     the project root for full license information.
// </copyright>
// <auto-generated>
// Sourced from NuGet package. Will be overwritten with package update except in Spritely.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Spritely.Recipes
{
    /// <summary>
    /// Represents an object capable of signing JSON web tokens
    /// </summary>
    internal interface IJsonWebTokenSigner
    {
        /// <summary>
        /// Gets the name of the algorithm.
        /// </summary>
        /// <value>The name of the algorithm.</value>
        string AlgorithmName { get; }

        /// <summary>
        /// Signs the specified data.
        /// </summary>
        /// <param name="data">The data to sign.</param>
        /// <returns>The signed data.</returns>
        byte[] Sign(byte[] data);
    }
}
