// --------------------------------------------------------------------------------------------------------------------
// <copyright file="JsonConfigurationTest.cs">
//   Copyright (c) 2015. All rights reserved.
//   Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Spritely.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Spritely.Recipes.Test
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Security;
    using Newtonsoft.Json;
    using NUnit.Framework;

    [TestFixture]
    public class JsonConfigurationTest
    {
        private enum TestEnum
        {
            FirstType
        }

        [Test]
        public void Serializer_writes_camel_cased_properties()
        {
            var result = JsonConvert.SerializeObject(new CamelCasedPropertyTest(), JsonConfiguration.SerializerSettings);

            Assert.That(
                result,
                Is.EqualTo(
                    "{" + Environment.NewLine +
                    "  \"testName\": \"Hello\"" + Environment.NewLine +
                    "}"));
        }

        [Test]
        public void Serializer_writes_camel_cased_enumerations()
        {
            var result = JsonConvert.SerializeObject(new CamelCasedEnumTest(), JsonConfiguration.SerializerSettings);

            Assert.That(
                result,
                Is.EqualTo(
                    "{" + Environment.NewLine +
                    "  \"first\": \"firstType\"" + Environment.NewLine +
                    "}"));
        }

        [Test]
        public void Serializer_reads_and_writes_SecureString_types()
        {
            var serializedValue = "{" + Environment.NewLine +
                                  "  \"secure\": \"Password\"" + Environment.NewLine +
                                  "}";
            var deserialized = JsonConvert.DeserializeObject<SecureStringTest>(serializedValue, JsonConfiguration.SerializerSettings);

            var result = JsonConvert.SerializeObject(deserialized, JsonConfiguration.SerializerSettings);

            Assert.That(result, Is.EqualTo(serializedValue));
        }

        private class CamelCasedPropertyTest
        {
            [SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields",
                Justification = "Field is used by code external to test")]
            public string TestName = "Hello";
        }

        private class CamelCasedEnumTest
        {
            [SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields",
                Justification = "Field is used by code external to test")]
            public TestEnum First = TestEnum.FirstType;
        }

        [SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses",
            Justification = "Class is used by code external to test")]
        private class SecureStringTest
        {
#pragma warning disable 649
            [SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields",
                Justification = "Field is used by code external to test")]
            public SecureString Secure;
#pragma warning restore
        }
    }
}
