// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MustExtensions.cs">
//     Copyright (c) 2016. All rights reserved. Licensed under the MIT license. See LICENSE file in
//     the project root for full license information.
// </copyright>
// <auto-generated>
// Sourced from NuGet package. Will be overwritten with package update except in Spritely.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Spritely.Recipes
{
    /// <summary>
    ///     Contains Must extension methods.
    /// </summary>
#if !RecipesProject
    [System.Diagnostics.DebuggerStepThrough]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Spritely.Recipes", "See package version number")]
#pragma warning disable 0436
#endif
    internal static partial class MustExtensions
    {
        /// <summary>
        /// Starts a requirement that certain objects Must meet to pass validation.
        /// </summary>
        /// <typeparam name="T">The type containing objects to be validated.</typeparam>
        /// <param name="objects">The objects.</param>
        /// <returns>A context for building up validation requirements.</returns>
        public static MustContext<T> Must<T>(this T objects) where T : class
        {
            return new MustContext<T>(objects);
        }
    }
#if !RecipesProject
#pragma warning restore 0436
#endif
}
