// --------------------------------------------------------------------------------------------------------------------
// <copyright file="GoogleAuthorizerSettings.cs">
//     Copyright (c) 2016. All rights reserved. Licensed under the MIT license. See LICENSE file in
//     the project root for full license information.
// </copyright>
// <auto-generated>
// Sourced from NuGet package. Will be overwritten with package update except in Spritely.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Spritely.Recipes
{
    using System.Security;

#if !RecipesProject
    [System.Diagnostics.DebuggerStepThrough]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Spritely.Recipes", "See package version number")]
#endif

    /// <summary>
    /// Provides settings for a GoogleAuthorizer.
    /// </summary>
    public class GoogleAuthorizerSettings
    {
        /// <summary>
        /// Gets or sets the certificate file.
        /// </summary>
        /// <value>The certificate file.</value>
        public string CertificateFile { get; set; }

        /// <summary>
        /// Gets or sets the certificate password.
        /// </summary>
        /// <value>The certificate password.</value>
        public SecureString CertificatePassword { get; set; }

        /// <summary>
        /// Gets or sets the service account.
        /// </summary>
        /// <value>
        /// The service account.
        /// </value>
        public string ServiceAccount { get; set; }
    }
}
