// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FunctionalTest.cs">
//   Copyright (c) 2017. All rights reserved.
//   Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Spritely.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Spritely.Recipes.Test
{
    using System;
    using System.Collections.Generic;
    using FluentAssertions;
    using NUnit.Framework;

    [TestFixture]
    public class FunctionalTest
    {
        [Test]
        public void AsFunc_throws_on_null_arguments()
        {
            Assert.Throws<ArgumentNullException>(() => (null as Action<string>).AsFunc());
        }

        [Test]
        public void AsFunc_result_calls_source_action_when_called()
        {
            var value = "Original value";

            Action<string> myAction = x => { value = x; };
            var myFunc = myAction.AsFunc();

            value.Should().Be("Original value");

            myFunc("New value");

            value.Should().Be("New value");
        }

        [Test]
        public void ForEach_throws_on_null_arguments()
        {
            var list = new List<object>();

            Assert.Throws<ArgumentNullException>(() => (null as IEnumerable<object>).ForEach(o => { }));
            Assert.Throws<ArgumentNullException>(() => list.ForEach(null));
        }

        [Test]
        public void ForEach_does_not_call_action_when_list_is_empty()
        {
            var list = new List<object>();
            var called = false;

            list.ForEach(_ => { called = true; });

            called.Should().BeFalse();
        }

        [Test]
        public void ForEach_calls_action_expected_number_of_times_with_expected_value_each_time()
        {
            var list = new List<int> { 1, 2, 3, 4 };
            var sum = 0;

            list.ForEach(value => { sum += value; });

            Assert.That(sum, Is.EqualTo(10));
        }

        [Test]
        public void Sort_throws_on_null_arguments()
        {
            Assert.Throws<ArgumentNullException>(() => (null as IEnumerable<int>).Sort());
        }

        [Test]
        public void Sort_sorts_the_provided_enumeration()
        {
            IEnumerable<int> source = new List<int> { 580, 12, 204, -4, 4, -90 };
            var result = source.Sort();

            result.Should().ContainInOrder(-90, -4, 4, 12, 204, 580);
        }
    }
}
